// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGp-5W1wMi-5CuLG8cAQ0CVRWO8w8-k6Y',
    appId: '1:448345543449:web:74f9fba632447dedf4ab88',
    messagingSenderId: '448345543449',
    projectId: 'brightway-d41b7',
    authDomain: 'brightway-d41b7.firebaseapp.com',
    databaseURL: 'https://brightway-d41b7-default-rtdb.firebaseio.com',
    storageBucket: 'brightway-d41b7.firebasestorage.app',
    measurementId: 'G-ME70FYWYCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMPS2MaLkV0OVA2kcgEUJ31Wp-daDFCXI',
    appId: '1:448345543449:android:a94433135635ffa0f4ab88',
    messagingSenderId: '448345543449',
    projectId: 'brightway-d41b7',
    databaseURL: 'https://brightway-d41b7-default-rtdb.firebaseio.com',
    storageBucket: 'brightway-d41b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKFOHhUy1G74nx15Oh311S-H0jOpJp7Gs',
    appId: '1:448345543449:ios:1927a6c02b34d2e5f4ab88',
    messagingSenderId: '448345543449',
    projectId: 'brightway-d41b7',
    databaseURL: 'https://brightway-d41b7-default-rtdb.firebaseio.com',
    storageBucket: 'brightway-d41b7.firebasestorage.app',
    iosBundleId: 'com.example.brightway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKFOHhUy1G74nx15Oh311S-H0jOpJp7Gs',
    appId: '1:448345543449:ios:1927a6c02b34d2e5f4ab88',
    messagingSenderId: '448345543449',
    projectId: 'brightway-d41b7',
    databaseURL: 'https://brightway-d41b7-default-rtdb.firebaseio.com',
    storageBucket: 'brightway-d41b7.firebasestorage.app',
    iosBundleId: 'com.example.brightway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGp-5W1wMi-5CuLG8cAQ0CVRWO8w8-k6Y',
    appId: '1:448345543449:web:8956a669b99efe8af4ab88',
    messagingSenderId: '448345543449',
    projectId: 'brightway-d41b7',
    authDomain: 'brightway-d41b7.firebaseapp.com',
    databaseURL: 'https://brightway-d41b7-default-rtdb.firebaseio.com',
    storageBucket: 'brightway-d41b7.firebasestorage.app',
    measurementId: 'G-M9D049RFE9',
  );
}
